spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mediaapp
    username: mediaapp_user
    password: mediaapp_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.tvz.mediaapp: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: NGRkNGI5YjVlYmJjM2VkN2U4YjZkNzJmZDE4MmNlZWI2ZDM4ODdkYmYxMWY2MjRlM2Q5ZDMxNzM0MGI3NDQ0MA==
  expiration-ms: 3600000 # 1 hour
  refresh-token-expiration-ms: 604800000 # 7 days

aws:
  region: eu-north-1
  s3:
    bucket-name: media-app-storage-tvz-8675309
    presigned-url-expiration-minutes: 15

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}